/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.next;
import controller.DEstego;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author anggy
 */
public class awal extends javax.swing.JFrame {

    /**
     * Creates new form awal
     */
    public awal() {
        initComponents();
        this.setLocationRelativeTo(null);
        about2.setVisible(false);
        kelompok.setVisible(false);
        c.setVisible(false);
    }
    String location;

    public void addUpload(ActionListener listener) {
        upload.addActionListener(listener);
    }

    public void addNext(ActionListener listener) {
        next.addActionListener(listener);
    }

    public void setURL(String url) {
        this.url.setText(url);
    }

    public String getFileHasil() {
        return fileHasil.getText();
    }

    public JLabel setImage() {
        return gambar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c = new javax.swing.JLabel();
        kelompok = new javax.swing.JLabel();
        gambar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        upload = new javax.swing.JButton();
        fileHasil = new javax.swing.JTextField();
        about2 = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c.setFont(new java.awt.Font("Play", 3, 24)); // NOI18N
        c.setForeground(new java.awt.Color(255, 255, 255));
        c.setText("Kelompok 16C Kriptografi");
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 310, 30));

        kelompok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/kelompok.png"))); // NOI18N
        getContentPane().add(kelompok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 520));
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 450, 260));

        jLabel6.setFont(new java.awt.Font("Play", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Your image :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 90, -1));

        url.setEnabled(false);
        getContentPane().add(url, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 190, -1));

        upload.setText("Upload");
        upload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadMouseClicked(evt);
            }
        });
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        getContentPane().add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 90, -1));

        fileHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileHasilActionPerformed(evt);
            }
        });
        getContentPane().add(fileHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 270, -1));

        about2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/about me.png"))); // NOI18N
        about2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                about2MouseExited(evt);
            }
        });
        getContentPane().add(about2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, 140, 30));

        about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutMouseExited(evt);
            }
        });
        getContentPane().add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, 130, 30));

        next.setText("NEXT");
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 80, 30));

        jLabel5.setFont(new java.awt.Font("Play", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("file name encrypt : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Program Studi Sistem Informasi, Universitas Jember");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 584, 370, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controller/kripto.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed


    }//GEN-LAST:event_uploadActionPerformed

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked

    }//GEN-LAST:event_nextMouseClicked

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

    }//GEN-LAST:event_nextActionPerformed

    private void uploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadMouseClicked


    }//GEN-LAST:event_uploadMouseClicked

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
        about2.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseEntered

    private void about2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about2MouseClicked
        kelompok.setVisible(true);
        c.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_about2MouseClicked

    private void fileHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileHasilActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_fileHasilActionPerformed

    private void about2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about2MouseExited
        kelompok.setVisible(false);
        c.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_about2MouseExited

    private void aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseExited
        about2.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel about2;
    private javax.swing.JLabel c;
    private javax.swing.JTextField fileHasil;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel kelompok;
    private javax.swing.JButton next;
    private javax.swing.JButton upload;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables

}
